// DESCRIPTION: Verilator: Verilog Test module
//
// This file ONLY is placed under the Creative Commons Public Domain.
// SPDX-FileCopyrightText: 2026 Antmicro
// SPDX-License-Identifier: CC0-1.0

module t (
    input clk
);

    integer cyc = 0;

    always @(posedge clk) begin
        cyc <= cyc + 1;
        if (cyc == 5) begin
            once_at_five: assert (cyc == 5);
        end
        if (cyc == 9) begin
            $write("*-* All Finished *-*\n");
            $finish;
        end
    end

    always_passes: assert property (@(posedge clk) cyc < 20);

endmodule
